name: Node.js CI

on:
  push:
    branches: [ "main" ] # أو اسم الفرع الخاص بك
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # يتيح لك تشغيل البوت يدوياً من GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 23.x
      uses: actions/setup-node@v4
      with:
        node-version: 23.x # نسخة LTS المستقرة
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --ignore-scripts
        npm install chalk@4.1.2 --legacy-peer-deps

    - name: Start Bot
      run: node index.js
      env:
        SESSION_ID: ${{ secrets.SESSION_ID }} # ضع كود الجلسة في Secrets
        
